# Generated by Django 4.2.7 on 2025-09-23 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CIGAN E-Store', max_length=100)),
                ('site_description', models.TextField(default='Your premier destination for electronics and stationery')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/favicons/')),
                ('contact_email', models.EmailField(default='support@estore.com', max_length=254)),
                ('contact_phone', models.CharField(default='+000 000 0000', max_length=20)),
                ('address', models.TextField(default='123 Business Street, City, Country')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')])),
                ('secondary_color', models.CharField(default='#8B5CF6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')])),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=5.99, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('enable_registration', models.BooleanField(default=True)),
                ('enable_guest_checkout', models.BooleanField(default=True)),
                ('enable_reviews', models.BooleanField(default=True)),
                ('enable_wishlist', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('order_notifications', models.BooleanField(default=True)),
                ('stock_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
