# Generated by Django 4.2.7 on 2025-10-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accept_mastercard',
            field=models.BooleanField(default=True, help_text='Accept MasterCard payments'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accept_paypal',
            field=models.BooleanField(default=True, help_text='Accept PayPal payments'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accept_visa',
            field=models.BooleanField(default=True, help_text='Accept Visa payments'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='E-Store. All rights reserved.', help_text='Copyright text', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='follow_us_text',
            field=models.CharField(default='Follow us', help_text='Text for social media links', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_address',
            field=models.TextField(default='Online Market, Your City', help_text='Address displayed in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(default='Your premier online store for Electronics & Stationery. Quality products, fast delivery, and excellent customer service.', help_text='Description displayed in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_email',
            field=models.EmailField(default='support@estore.com', help_text='Email displayed in footer', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_phone',
            field=models.CharField(default='+000 000 0000', help_text='Phone displayed in footer', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_email',
            field=models.EmailField(default='support@estore.com', help_text='Email displayed in header', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_phone',
            field=models.CharField(default='+000 000 0000', help_text='Phone displayed in header', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_url',
            field=models.URLField(blank=True, help_text='Privacy policy URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_url',
            field=models.URLField(blank=True, help_text='Terms of service URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL', null=True),
        ),
    ]
