# Generated by Django 4.2.7 on 2025-09-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_locations', to='products.product')),
            ],
            options={
                'db_table': 'book_locations',
                'ordering': ['row', 'column'],
                'unique_together': {('row', 'column')},
            },
        ),
    ]
